/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleCoffeesIndexRouteImport } from './routes/$locale/coffees/index'
import { Route as LocaleCoffeesCoffeeIdRouteImport } from './routes/$locale/coffees/$coffeeId'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCoffeesIndexRoute = LocaleCoffeesIndexRouteImport.update({
  id: '/coffees/',
  path: '/coffees/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCoffeesCoffeeIdRoute = LocaleCoffeesCoffeeIdRouteImport.update({
  id: '/coffees/$coffeeId',
  path: '/coffees/$coffeeId',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/coffees/$coffeeId': typeof LocaleCoffeesCoffeeIdRoute
  '/$locale/coffees/': typeof LocaleCoffeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/coffees/$coffeeId': typeof LocaleCoffeesCoffeeIdRoute
  '/$locale/coffees': typeof LocaleCoffeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/coffees/$coffeeId': typeof LocaleCoffeesCoffeeIdRoute
  '/$locale/coffees/': typeof LocaleCoffeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/coffees/$coffeeId'
    | '/$locale/coffees/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$locale' | '/$locale/coffees/$coffeeId' | '/$locale/coffees'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/coffees/$coffeeId'
    | '/$locale/coffees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/coffees/': {
      id: '/$locale/coffees/'
      path: '/coffees'
      fullPath: '/$locale/coffees/'
      preLoaderRoute: typeof LocaleCoffeesIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/coffees/$coffeeId': {
      id: '/$locale/coffees/$coffeeId'
      path: '/coffees/$coffeeId'
      fullPath: '/$locale/coffees/$coffeeId'
      preLoaderRoute: typeof LocaleCoffeesCoffeeIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleCoffeesCoffeeIdRoute: typeof LocaleCoffeesCoffeeIdRoute
  LocaleCoffeesIndexRoute: typeof LocaleCoffeesIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleCoffeesCoffeeIdRoute: LocaleCoffeesCoffeeIdRoute,
  LocaleCoffeesIndexRoute: LocaleCoffeesIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
